name: ehoa
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  auth0_flutter: ^1.1.0
  awesome_notifications: any
  blur: ^3.1.0
  bottom_sheet: ^3.1.2
  change_app_package_name: ^1.1.0
  cupertino_icons: ^1.0.2
  dio: ^5.0.2
  dotted_border: ^2.0.0+3
  dotted_decoration: ^2.0.0
  dropdown_search: ^5.0.6
  expandable_text: ^2.3.0
  fast_cached_network_image: ^1.2.0
  file_picker: ^5.2.2
  firebase_auth: ^4.6.2
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  firebase_remote_config: ^4.2.2
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^5.0.11
  flutter_image_slideshow: ^0.1.5
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^8.2.0
  flutter_native_splash: ^2.2.0+1
  flutter_screenutil: ^5.5.3+2
  flutter_super_html_viewer: ^0.1.0
  flutter_svg: any
  get: ^4.6.5
  get_it: ^7.2.0
  google_sign_in: ^6.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^0.13.5
  iconly: ^1.0.1
  iconsax: ^0.0.8
  intl: any
  ionicons: ^0.2.2
  logger: ^1.1.0
  lottie: ^2.0.0
  notification_permissions: ^0.6.1
  path_provider: ^2.0.14
  radar_chart: ^2.1.0
  rename_app: ^1.1.0
  shared_preferences: ^2.0.17
  sign_in_with_apple: ^4.3.0
  spring: ^2.0.2
  syncfusion_flutter_gauges: ^21.2.5
  table_calendar: ^3.0.8
  url_launcher_android: ^6.0.31
dev_dependencies:
  build_runner: # generate dart files
    null
  flutter_lints: null

  flutter_test:
    sdk: flutter
  hive_generator: # generate hive files
    null

  integration_test:
    sdk: flutter
  mockito: null

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"

flutter_native_splash:
  background_image: assets/images/splash.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/vectors/
    - assets/vectors/moons/
    - assets/fonts/
    - assets/gifs/
    - animations/

  fonts:
    - family: Inter-Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
    - family: Inter-Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
    - family: Inter-SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
    - family: Inter-Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 700
    - family: Bely-Display-W00-Regular
      fonts:
        - asset: assets/fonts/Bely-Display-W00-Regular.ttf
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo-SemiBold.ttf
          weight: 900
